{
 "title": "Postgres Benchmarks",
 "time": { "from": "2023-02-15T19:49:32.329Z", "to": "2023-02-15T20:09:55.848Z" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   },
   {
    "name": "system",
    "query": {
     "query": "label_values(k6_vus_gauge,system)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\", system=\"$system\"})",
     "legendFormat": "{{testrun}}"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    },
    {
     "expr": "k6_vus_gauge{testrun=\"$testrun\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Inserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(testrun) (k6_inserts_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    }
   ]
  },
  {
   "title": "IPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum by(testrun) (rate(k6_inserts_counter{testrun=\"$testrun\"}[$__interval]))",
     "legendFormat": "{{testrun}}"
    },
    {
     "expr": "sum by(testrun) (rate(k6_failed_counter{testrun=\"$testrun\"}[$__interval]))",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Insert Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(k6_insert_trend_current_gauge{testrun=\"$testrun\"}[$__interval])) by (testrun)",
     "legendFormat": "ins"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes_gauge / 1024 / 1024 / 1024",
     "legendFormat": "{{host}}"
    },
    {
     "expr": "process_virtual_memory_bytes_gauge ",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total_counter[$__rate_interval])",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_open_fds_gauge", "legendFormat": "{{host}}" }
   ]
  }
 ]
}