{
 "title": "PostgREST Benchmarks",
 "time": { "from": "2023-02-16T09:26:57.250Z", "to": "2023-02-16T09:42:33.295Z" },
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    },
    {
     "expr": "k6_vus_gauge{testrun=\"$testrun\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(testrun, status) (k6_http_reqs_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(testrun, status) (rate(k6_http_reqs_counter{testrun=\"$testrun\"}[$__interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "App Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(k6_http_req_duration_current_gauge{testrun=\"$testrun\"}[$__interval])) by (status)",
     "legendFormat": "{{status}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(k6_http_req_duration_current_gauge{testrun=\"$testrun\"}[$__interval])) by (le))",
     "legendFormat": "p95 {{status}}"
    }
   ]
  },
  {
   "title": "Data Transferred",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (testrun) (rate (k6_data_received_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum by (testrun) (rate (k6_data_received_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}