{
 "title": "StorageAPI benchmarks",
 "time": { "from": "2023-02-14T06:21:30.366Z", "to": "2023-02-14T06:32:11.987Z" },
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    }
   ]
  },
  {
   "title": "Requests Counter",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (status) (k6_http_reqs_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (status)  (k6_http_req_duration_current_gauge{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by (status) (rate (k6_http_reqs_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Data received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (status) (k6_data_received_counter{testrun=\"$testrun\"})",
     "legendFormat": "received"
    },
    {
     "expr": "sum by (status) (k6_data_sent_counter{testrun=\"$testrun\"})",
     "legendFormat": "sent"
    }
   ]
  },
  {
   "title": "MB/s",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (testrun) (rate (k6_data_received_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "sum by (testrun) (rate (k6_data_sent_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "sent"
    }
   ]
  }
 ]
}