{
 "title": "Performance Results",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Test run time range",
   "type": "table",
   "gridPos": { "h": 4, "w": 16, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_vus_gauge{testrun=\"$testrun\"}"
    }
   ]
  },
  { "title": "VUs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "vus"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "vus"
    }
   ]
  },
  { "title": "Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})",
     "legendFormat": "latency"
    },
    {
     "expr": "quantile_over_time(0.99, max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})[$__range:10s])",
     "legendFormat": "p99"
    },
    {
     "expr": "quantile_over_time(0.9, max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})[$__range:10s])",
     "legendFormat": "p90"
    },
    {
     "expr": "quantile_over_time(0.75, max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})[$__range:10s])",
     "legendFormat": "p75"
    },
    {
     "expr": "quantile_over_time(0.5, max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})[$__range:10s])",
     "legendFormat": "med"
    },
    {
     "expr": "quantile_over_time(0.01, max by (testrun) (k6_latency_trend_current_gauge{testrun=\"$testrun\"})[$__range:10s])",
     "legendFormat": "p0.01"
    }
   ]
  },
  {
   "title": "Messages from Realtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (irate(k6_received_updates_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "msgs"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_latency_trend_current_gauge{testrun=\"$testrun\"}",
     "legendFormat": "latency {{host}}"
    },
    {
     "expr": "quantile_over_time(0.99, k6_latency_trend_current_gauge{testrun=\"$testrun\"}[$__range:10s])",
     "legendFormat": "p99  {{host}}"
    },
    {
     "expr": "quantile_over_time(0.9, k6_latency_trend_current_gauge{testrun=\"$testrun\"}[$__range:10s])",
     "legendFormat": "p90  {{host}}"
    },
    {
     "expr": "quantile_over_time(0.75, k6_latency_trend_current_gauge{testrun=\"$testrun\"}[$__range:10s])",
     "legendFormat": "p75  {{host}}"
    },
    {
     "expr": "quantile_over_time(0.5, k6_latency_trend_current_gauge{testrun=\"$testrun\"}[$__range:10s])",
     "legendFormat": "med  {{host}}"
    },
    {
     "expr": "quantile_over_time(0.01, k6_latency_trend_current_gauge{testrun=\"$testrun\"}[$__range:10s])",
     "legendFormat": "p0.01  {{host}}"
    }
   ]
  },
  {
   "title": "Messages from Realtime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(k6_received_updates_counter{testrun=\"$testrun\"}[$__rate_interval])",
     "legendFormat": "msgs  {{host}}"
    }
   ]
  },
  { "title": "Performance Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Throughput (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (testrun) (irate(k6_data_sent_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "received by realtime"
    },
    {
     "expr": "sum by (testrun) (irate(k6_data_received_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "sent by realtime"
    }
   ]
  },
  {
   "title": "Messages/sec",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (irate(k6_ws_msgs_sent_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "received by realtime"
    },
    {
     "expr": "sum by (testrun) (irate(k6_ws_msgs_received_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "sent by realtime"
    }
   ]
  },
  { "title": "WS Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "WS session duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "k6_ws_session_duration_current_gauge{testrun=\"$testrun\"}",
     "legendFormat": "ws_session_duration {{host}}"
    }
   ]
  },
  {
   "title": "WS connecting time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (testrun) (k6_ws_connecting_current_gauge{testrun=\"$testrun\"})",
     "legendFormat": "connecting_time"
    }
   ]
  },
  {
   "title": "All WS sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_ws_sessions_counter{testrun=\"$testrun\"})",
     "legendFormat": "total_ws_sessions"
    }
   ]
  },
  {
   "title": "New WS sessions",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (testrun) (irate(k6_ws_sessions_counter{testrun=\"$testrun\"}[$__rate_interval]))",
     "legendFormat": "new_ws_session"
    }
   ]
  },
  { "title": "Loader Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_max_bytes_gauge / 1024 / 1024 / 1024",
     "legendFormat": "max {{host}}"
    },
    {
     "expr": "process_virtual_memory_bytes_gauge",
     "legendFormat": "used {{host}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total_counter[$__rate_interval])",
     "legendFormat": "used  {{host}}"
    }
   ]
  },
  {
   "title": "FDs",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "process_max_fds_gauge", "legendFormat": "max {{host}}" },
    { "expr": "process_open_fds_gauge", "legendFormat": "open {{host}}" }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "go_goroutines_gauge{}", "legendFormat": "num {{host}}" }
   ]
  },
  { "title": "App Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(fly_instance_memory_mem_total{app=~\"realtime-qa\",region=~\".*\",host=~\".*\"})",
     "legendFormat": "total"
    },
    {
     "expr": "avg(fly_instance_memory_mem_total{app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}) - avg(fly_instance_memory_mem_free{app=~\"realtime-qa\",region=~\".*\",host=~\".*\"})",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"1\",app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}[$__rate_interval]))",
     "legendFormat": "1m"
    },
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"5\",app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}[$__rate_interval]))",
     "legendFormat": "5m"
    },
    {
     "expr": "max(max_over_time(fly_instance_load_average{minutes=\"15\",app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}[$__rate_interval]))",
     "legendFormat": "15m"
    }
   ]
  },
  { "title": "App Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Data Transfer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(fly_instance_net_sent_bytes{device=\"eth0\",app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}[$__rate_interval]))",
     "legendFormat": "sent"
    },
    {
     "expr": "sum(rate(fly_instance_net_recv_bytes{device=\"eth0\",app=~\"realtime-qa\",region=~\".*\",host=~\".*\"}[$__rate_interval]))",
     "legendFormat": "recv"
    }
   ]
  },
  {
   "title": "App concurrency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "fly_app_concurrency{app=\"realtime-qa\"}",
     "legendFormat": "instance-{{instance}}"
    }
   ]
  }
 ]
}