{
 "title": "Image Resizing Benchmarks",
 "time": { "from": "2023-02-01T12:06:08.456Z", "to": "2023-02-01T12:21:03.460Z" },
 "templating": {
  "list": [
   {
    "name": "testrun",
    "query": {
     "query": "label_values(k6_vus_gauge,testrun)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Load", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Resize Requests by Status (consecutive)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun, group, name) (k6_resized_statuses_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Resize Requests by Status (batch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by (testrun, group, name) (k6_resized_batch_statuses_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Http Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 17, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (status) (k6_http_req_blocked_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "blocked {{status}}"
    },
    {
     "expr": "avg by (status) (k6_http_req_connecting_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "connecting {{status}}"
    },
    {
     "expr": "avg by (status) (k6_http_req_handshake_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "handshake {{status}}"
    },
    {
     "expr": "avg by (status) (k6_http_req_waiting_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "waiting {{status}}"
    },
    {
     "expr": "avg by (status) (k6_http_req_sending_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "sending {{status}}"
    },
    {
     "expr": "avg by (status) (k6_http_req_receiving_current_gauge{group=\"::resize requests\", testrun=\"$testrun\"})",
     "legendFormat": "receiving {{status}}"
    }
   ]
  },
  {
   "title": "All HTTP requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by (testrun, status) (k6_http_reqs_counter{testrun=\"$testrun\"})",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "VUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 17 },
   "targets": [
    {
     "expr": "sum by (testrun) (k6_vus_gauge{testrun=\"$testrun\"})",
     "legendFormat": "{{testrun}}"
    }
   ]
  },
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Number of Request",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_requests_total[$__range]))"
    }
   ]
  },
  {
   "title": "Number of Requests (Over Time)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 26 },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_requests_total))[$__rate_interval]",
     "legendFormat": "Request Number"
    }
   ]
  },
  {
   "title": "Request Duration Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(imgproxy_processing_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "0.99p"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(imgproxy_processing_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "0.95p"
    },
    {
     "expr": "histogram_quantile(0.70, sum(rate(imgproxy_processing_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "0.70p"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(imgproxy_processing_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "0.50p"
    },
    {
     "expr": "histogram_quantile(0.20, sum(rate(imgproxy_processing_duration_seconds_bucket[$__range])) by (le))",
     "legendFormat": "0.20p"
    }
   ]
  },
  {
   "title": "Request Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (instance) (increase(imgproxy_requests_total))[$__range]",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(imgproxy_requests_total[$__rate_interval]))",
     "legendFormat": "total req"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "expr": "sum(rate(imgproxy_request_duration_seconds_bucket[$__range]))",
     "legendFormat": "total req"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    { "expr": "aws_ecs" }
   ]
  },
  {
   "title": "Buffer Max Size",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_buffer_size_bytes_sum[$__range])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "VIPS Memory",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(imgproxy_vips_memory_bytes[$__range])",
     "legendFormat": "Current Memory"
    },
    {
     "expr": "sum(imgproxy_vips_max_memory_bytes[$__range])",
     "legendFormat": "Max Memory"
    }
   ]
  },
  {
   "title": "Buffer Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_buffer_size_bytes_sum)[$__range]) by (type)",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Processing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Processing Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum((rate(imgproxy_request_span_duration_seconds_bucket))[$__range]) by (span, le)",
     "legendFormat": "{{span}}"
    }
   ]
  },
  {
   "title": "Image Resizing in Progress (Right Now)",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 11, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(imgproxy_images_in_progress)",
     "legendFormat": "in progress"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 77 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_errors_total[$__range]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 77 },
   "targets": [
    {
     "expr": "sum(increase(imgproxy_errors_total))[$__range]",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Spending most of the time",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(rate(imgproxy_request_span_duration_seconds_bucket[$__range])) by (span)",
     "legendFormat": "{{ span }}"
    }
   ]
  }
 ]
}